"""
Synthetic Shopify-like event generator.

Design principle: behavior is MODELED, not sampled independently per row.
A session is generated by walking a state machine; events are emitted along
the walk. This is what makes the funnel internally consistent (e.g., a
purchase always has a preceding checkout_started event).
"""
from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Iterator

import numpy as np
import pandas as pd
from faker import Faker

from src import config as cfg
from src.utils import get_logger

logger = get_logger(__name__)
fake = Faker()


# ---------------------------------------------------------------------------
# Low-level helpers
# ---------------------------------------------------------------------------

def _make_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


def _sample_device(rng: np.random.Generator) -> str:
    return str(rng.choice(cfg.DEVICES, p=cfg.DEVICE_WEIGHTS))


def _sample_source(rng: np.random.Generator) -> str:
    return str(rng.choice(cfg.TRAFFIC_SOURCES, p=cfg.SOURCE_WEIGHTS))


def _sample_order_value(rng: np.random.Generator) -> float:
    """Right-skewed order value via log-normal."""
    return float(np.round(rng.lognormal(cfg.ORDER_VALUE_MEAN_LOG,
                                        cfg.ORDER_VALUE_SIGMA_LOG), 2))


def _jitter(ts: datetime, rng: np.random.Generator,
            min_sec: int = 5, max_sec: int = 900) -> datetime:
    return ts + timedelta(seconds=int(rng.integers(min_sec, max_sec)))


def _prob(base: float, *multipliers: float) -> float:
    """Apply multiplicative segment effects, clamped to [0, 1]."""
    p = base
    for m in multipliers:
        p *= m
    return float(np.clip(p, 0.0, 1.0))


# ---------------------------------------------------------------------------
# Session state machine
# ---------------------------------------------------------------------------

@dataclass
class SessionResult:
    """What a completed session walk produced."""
    traffic_rows: list[dict]
    cart_rows: list[dict]
    checkout_rows: list[dict]
    order_rows: list[dict]


def _walk_session(
    rng: np.random.Generator,
    session_id: str,
    user_id: str,
    device: str,
    source: str,
    start_ts: datetime,
) -> SessionResult:
    """
    Walk one session through the funnel, emitting events.

    State transitions use MODULATED probabilities so segments differ.
    Timing is monotonic (mostly) with occasional out-of-order jitter
    introduced deliberately in the clean-up pass.
    """
    traffic_rows: list[dict] = []
    cart_rows: list[dict] = []
    checkout_rows: list[dict] = []
    order_rows: list[dict] = []

    ts = start_ts
    source_for_row = source

    # ---- 1. Product view(s) ----
    n_views = 1
    if rng.random() < cfg.P_VIEW_MULTIPLE_PRODUCTS:
        n_views = int(rng.integers(2, 5))

    viewed_products: list[str] = []
    for _ in range(n_views):
        pid = f"{cfg.PRODUCT_ID_PREFIX}{rng.integers(1000, 1000 + cfg.N_PRODUCTS)}"
        viewed_products.append(pid)
        traffic_rows.append({
            "session_id": session_id,
            "user_id": user_id,
            "timestamp": ts,
            "traffic_source": source_for_row,
            "device": device,
            "product_id_viewed": pid,
        })
        ts = _jitter(ts, rng, 5, 120)

    # ---- 2. Add to cart? ----
    p_atc = _prob(
        cfg.P_ADD_TO_CART_GIVEN_VIEW,
        cfg.DEVICE_MULTIPLIERS[device]["atc"],
        cfg.SOURCE_MULTIPLIERS.get(source, {"atc": 1.0})["atc"],
    )
    added = rng.random() < p_atc

    in_cart: list[str] = []
    if added:
        # Add 1-3 products (subset of viewed + possibly new)
        n_add = int(rng.integers(1, 4))
        for i in range(n_add):
            pid = viewed_products[i % len(viewed_products)] \
                if i < len(viewed_products) \
                else f"{cfg.PRODUCT_ID_PREFIX}{rng.integers(1000, 1000 + cfg.N_PRODUCTS)}"
            cart_rows.append({
                "session_id": session_id,
                "user_id": user_id,
                "timestamp": ts,
                "action": "add_to_cart",
                "product_id": pid,
            })
            in_cart.append(pid)
            ts = _jitter(ts, rng, 10, 240)

        # Possibly remove one
        if rng.random() < cfg.P_REMOVE_FROM_CART and in_cart:
            removed = in_cart.pop(int(rng.integers(0, len(in_cart))))
            cart_rows.append({
                "session_id": session_id,
                "user_id": user_id,
                "timestamp": ts,
                "action": "remove_from_cart",
                "product_id": removed,
            })
            ts = _jitter(ts, rng, 10, 240)

        # If cart emptied, stop here.
        if not in_cart:
            added = False

    # ---- 3. Checkout? ----
    reached_checkout = False
    checkout_id: str | None = None
    payment_attempted = False
    if added:
        p_checkout = _prob(
            cfg.P_CHECKOUT_GIVEN_CART,
            cfg.DEVICE_MULTIPLIERS[device]["checkout"],
            cfg.SOURCE_MULTIPLIERS.get(source, {"checkout": 1.0})["checkout"],
        )
        reached_checkout = rng.random() < p_checkout

    if reached_checkout:
        cart_value = float(np.round(
            sum(_sample_order_value(rng) for _ in in_cart), 2))
        checkout_id = _make_id("co")
        checkout_rows.append({
            "checkout_id": checkout_id,
            "session_id": session_id,
            "user_id": user_id,
            "timestamp": ts,
            "checkout_status": "checkout_started",
            "cart_value": cart_value,
        })
        ts = _jitter(ts, rng, 15, 300)

        # Payment attempted?
        if rng.random() < cfg.P_PAYMENT_ATTEMPTED_GIVEN_CHECKOUT:
            payment_attempted = True
            checkout_rows.append({
                "checkout_id": checkout_id,
                "session_id": session_id,
                "user_id": user_id,
                "timestamp": ts,
                "checkout_status": "payment_attempted",
                "cart_value": cart_value,
            })
            ts = _jitter(ts, rng, 10, 180)

    # ---- 4. Purchase? ----
    purchased = False
    if payment_attempted:
        p_purchase = _prob(
            cfg.P_PURCHASE_GIVEN_PAYMENT_ATTEMPTED,
            cfg.DEVICE_MULTIPLIERS[device]["purchase"],
            cfg.SOURCE_MULTIPLIERS.get(source, {"purchase": 1.0})["purchase"],
        )
        purchased = rng.random() < p_purchase

    if purchased:
        order_value = _sample_order_value(rng)
        discount = 0.0
        if rng.random() < cfg.DISCOUNT_PROBABILITY:
            lo, hi = cfg.DISCOUNT_RANGE
            discount = float(np.round(order_value * rng.uniform(lo, hi), 2))

        status = str(rng.choice(
            list(cfg.ORDER_STATUS_WEIGHTS.keys()),
            p=list(cfg.ORDER_STATUS_WEIGHTS.values()),
        ))

        # One order row per purchased product (typical Shopify line-item shape)
        for pid in in_cart:
            order_rows.append({
                "order_id": _make_id("ord"),
                "session_id": session_id,
                "user_id": user_id,
                "timestamp": ts,
                "gross_revenue": order_value,
                "discount_applied": discount,
                "product_id": pid,
                "order_status": status,
            })
    else:
        # Payment failed (if we attempted) — record the failure
        if payment_attempted and checkout_id is not None:
            checkout_rows.append({
                "checkout_id": checkout_id,
                "session_id": session_id,
                "user_id": user_id,
                "timestamp": ts,
                "checkout_status": "payment_failed",
                "cart_value": cart_value,  # noqa: F821  (defined above when payment_attempted)
            })

    return SessionResult(traffic_rows, cart_rows, checkout_rows, order_rows)


# ---------------------------------------------------------------------------
# Top-level generation
# ---------------------------------------------------------------------------

def _daily_session_count(day_index: int, rng: np.random.Generator) -> int:
    """Sessions per day with weekend uplift and mild noise."""
    d = datetime.fromisoformat(cfg.SIMULATION_START) + timedelta(days=day_index)
    weekday = d.weekday()  # Mon=0 ... Sun=6
    base = cfg.BASE_DAILY_SESSIONS
    if weekday >= 5:
        base = int(base * cfg.WEEKEND_MULTIPLIER)
    noise = int(rng.normal(0, base * 0.08))
    return max(50, base + noise)


def generate_raw_events() -> dict[str, pd.DataFrame]:
    """
    Generate all four raw tables for the simulation window.

    Returns a dict of DataFrames keyed by table name.
    """
    rng = np.random.default_rng(cfg.RANDOM_SEED)
    start = datetime.fromisoformat(cfg.SIMULATION_START)

    traffic: list[dict] = []
    cart: list[dict] = []
    checkout: list[dict] = []
    orders: list[dict] = []

    # Pre-create a user pool so some users return across days.
    n_users = 4000
    user_ids = [f"usr_{i:06d}" for i in range(n_users)]

    for day in range(cfg.SIMULATION_DAYS):
        n_sessions = _daily_session_count(day, rng)
        for _ in range(n_sessions):
            # ~22% of sessions are returning users
            if rng.random() < 0.22:
                user_id = str(rng.choice(user_ids))
            else:
                user_id = _make_id("usr")

            session_id = _make_id("sess")
            device = _sample_device(rng)
            source = _sample_source(rng)

            # Random start time within the day, weighted toward business hours
            hour = int(np.clip(rng.normal(14, 4), 0, 23))
            minute = int(rng.integers(0, 60))
            second = int(rng.integers(0, 60))
            start_ts = start + timedelta(days=day, hours=hour,
                                         minutes=minute, seconds=second)

            result = _walk_session(rng, session_id, user_id, device, source, start_ts)
            traffic.extend(result.traffic_rows)
            cart.extend(result.cart_rows)
            checkout.extend(result.checkout_rows)
            orders.extend(result.order_rows)

    df_traffic = pd.DataFrame(traffic)
    df_cart = pd.DataFrame(cart)
    df_checkout = pd.DataFrame(checkout)
    df_orders = pd.DataFrame(orders)

    # ---------------------------------------------------------------
    # Deliberate data-quality imperfections (documented, not hidden).
    # These simulate real-world tracking issues. The DQ module reports
    # them; the staging SQL handles them defensively.
    # ---------------------------------------------------------------

    # 1. Missing traffic_source
    if not df_traffic.empty:
        mask = rng.random(len(df_traffic)) < cfg.DQ_MISSING_SOURCE_RATE
        df_traffic.loc[mask, "traffic_source"] = None

    # 2. Duplicate traffic rows (tracking double-fire)
    if not df_traffic.empty:
        n_dup = int(len(df_traffic) * cfg.DQ_DUPLICATE_TRAFFIC_RATE)
        if n_dup > 0:
            dup_idx = rng.choice(df_traffic.index, size=n_dup, replace=False)
            df_traffic = pd.concat(
                [df_traffic, df_traffic.loc[dup_idx]], ignore_index=True)

    # 3. Duplicate cart rows
    if not df_cart.empty:
        n_dup = int(len(df_cart) * cfg.DQ_DUPLICATE_CART_RATE)
        if n_dup > 0:
            dup_idx = rng.choice(df_cart.index, size=n_dup, replace=False)
            df_cart = pd.concat(
                [df_cart, df_cart.loc[dup_idx]], ignore_index=True)

    # 4. Invalid order statuses (typos / partial writes)
    if not df_orders.empty:
        mask = rng.random(len(df_orders)) < cfg.DQ_INVALID_ORDER_STATUS_RATE
        df_orders.loc[mask, "order_status"] = "unknwon"

    # 5. Orphan orders (order without a matching checkout session row)
    if not df_orders.empty and not df_checkout.empty:
        n_orphan = int(len(df_orders) * cfg.DQ_ORPHAN_ORDER_RATE)
        if n_orphan > 0:
            orphan_idx = rng.choice(df_orders.index, size=n_orphan, replace=False)
            # Corrupt session_id so it has no checkout
            df_orders.loc[orphan_idx, "session_id"] = [
                _make_id("sess_orphan") for _ in range(n_orphan)
            ]

    # 6. Shuffle timestamps slightly within each table to simulate
    #    out-of-order arrival. We sort by timestamp only when writing.
    for df in (df_traffic, df_cart, df_checkout, df_orders):
        if not df.empty:
            df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

    logger.info("Generated sessions: %d",
                df_traffic["session_id"].nunique() if not df_traffic.empty else 0)
    logger.info("traffic=%d cart=%d checkout=%d orders=%d",
                len(df_traffic), len(df_cart), len(df_checkout), len(df_orders))

    return {
        "traffic_logs": df_traffic,
        "cart_actions": df_cart,
        "checkout_events": df_checkout,
        "orders": df_orders,
    }


def validation_report(tables: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """
    Session-level funnel validation. This is what proves the generator
    is behaviorally realistic (not just random rows).
    """
    traffic = tables["traffic_logs"]
    cart = tables["cart_actions"]
    checkout = tables["checkout_events"]
    orders = tables["orders"]

    total_sessions = traffic["session_id"].nunique()
    atc_sessions = cart.loc[
        cart["action"] == "add_to_cart", "session_id"
    ].nunique() if not cart.empty else 0
    checkout_sessions = checkout["session_id"].nunique() if not checkout.empty else 0
    purchase_sessions = orders.loc[
        orders["order_status"] == "paid", "session_id"
    ].nunique() if not orders.empty else 0

    rows = [
        ("Total sessions", total_sessions),
        ("Product-view sessions", total_sessions),
        ("Add-to-cart sessions", atc_sessions),
        ("Checkout sessions", checkout_sessions),
        ("Purchase sessions", purchase_sessions),
    ]
    df = pd.DataFrame(rows, columns=["Stage", "Sessions"])
    df["Conversion from previous"] = [
        None,
        f"{total_sessions / max(total_sessions, 1):.2%}",
        f"{atc_sessions / max(total_sessions, 1):.2%}",
        f"{checkout_sessions / max(atc_sessions, 1):.2%}",
        f"{purchase_sessions / max(checkout_sessions, 1):.2%}",
    ]
    df["Cumulative conversion"] = [
        f"{total_sessions / max(total_sessions, 1):.2%}",
        f"{total_sessions / max(total_sessions, 1):.2%}",
        f"{atc_sessions / max(total_sessions, 1):.2%}",
        f"{checkout_sessions / max(total_sessions, 1):.2%}",
        f"{purchase_sessions / max(total_sessions, 1):.2%}",
    ]
    return df